library(here)
source(file.path(here(),"Scripts","functions.R"))
source(file.path(here(),"Scripts","global_var.R"))

maindir = here()

# Directories -------------------------------------------------------------
outdir = file.path(maindir, "output","scRNAseq", "MM468");  if(!dir.exists(outdir)){dir.create(outdir)}
QCdir <- file.path(outdir, "QC"); if(!dir.exists(QCdir)){dir.create(QCdir)}
resdir <- file.path(outdir, "Persister"); if(!dir.exists(resdir)){dir.create(resdir)}
resSUBdir <- file.path(resdir, paste0("Unsupervised")) ; if(!file.exists(resSUBdir)){dir.create(resSUBdir)}
RDatadir <- file.path(resSUBdir,"RData") ; if(!file.exists(RDatadir)){dir.create(RDatadir)}
RDatadirSamples <- file.path(RDatadir,"RData_perSample") ; if(!file.exists(RDatadirSamples)){dir.create(RDatadirSamples)}

# Replace GEO path with the path to the GEO directory downloaded on your computer (scRNA MM468)
GEOdir_scRNA_MM468 = file.path(maindir,"input","scRNAseq","MM468") 

# Load Data ---------------------------------------------------------------
BCmodel <- "MM468"

scRNA = list()
for(file in list.files(GEOdir_scRNA_MM468,pattern = ".*barcodes.tsv.gz", full.names = TRUE )){
  prefix = gsub("barcodes.tsv.gz", "", file)
  name = gsub("_barcodes.tsv.gz", "", basename(file))
  scRNA[[name]] = DropletUtils::read10xCounts(prefix, type = "prefix")
  gc()
}

# QC, normalization  ------------------------------------------------------
for(i in seq_along(umi)){
  umi = scRNA[[i]]
  name = names(scRNA)[i]
  keep_feat <- rowSums(counts(umi)>0)>0 #remove genes that are not expressed in any cells
  umi <- umi[keep_feat,]
  
  mt = which(grepl("^MT-", rowData(umi)[[2]]))
  ercc = which(grepl("ERCC", rowData(umi)[[2]]))
  control_features = rowData(umi)$ID[c(mt,ercc)]
  cellpool = seq_along(rowData(umi)[[2]])[-c(mt,ercc)]
  
  subsets = list("mt" = mt, "ercc" = ercc)
  rb.genes <- rowData(umi)[[1]][grep("^RP[SL]",rowData(umi)[[2]])]
  
  
  umi <- scater::addPerCellQC(umi, subsets = subsets)
  umi <- scater::addPerFeatureQC(umi)

  ##Manual quality filters:
  #Distribution of number of total detected features should be normal, get rid of the heavy right tail (<6000)
  umi$filter_by_expr_features <- (umi$detected<8000 & umi$detected>3000)
  #Distribution of number of total number of counts
  umi$filter_by_lib_size <- (umi$sum < 100000)
  #MT contamination
  umi$filter_by_MT_conta <- (umi$subsets_mt_percent<15)
  #Spike-in
  umi$filter_by_spikein <- (umi$subsets_ercc_percent<0.05)

  umi$use <- (umi$filter_by_lib_size & umi$filter_by_MT_conta & umi$filter_by_spikein & umi$filter_by_expr_features)

  umi.qc <- umi[,umi$use]
  
  #remove MT & ERCC genes from dataset for further analysis
  umi.qc <- umi.qc[-which(rowData(umi.qc)$ID %in% control_features),]
  dim(umi.qc)

  #Normalization by library size only
  sizeFactors(umi.qc) <- librarySizeFactors(umi.qc)
  umi.qc <- scater::logNormCounts(umi.qc) #normalized log2 expression values
  umi.qc <- scater::logNormCounts(umi.qc,log = FALSE) #normalized expression values


  pdf(file.path(QCdir,paste0(name,"_QC_scRNAseq.pdf")))
  scater::plotColData(umi,x="detected",y="subsets_mt_percent")
  scater::plotColData(umi,x="detected",y="subsets_ercc_percent")
  hist(umi$detected,breaks=100,xlim=c(0,10000),main=" Number of detected genes",xlab="NUMBER of GENES")
  abline(v=6000,col="red")
  abline(v=1500,col="red")
  hist(umi$sum,breaks=100, xlim=c(0,300000),main="Library size",xlab="TOTAL COUNTS")
  M <- median(umi$total_counts)
  abline(v=100000,col="red")
  dev.off()

  unc <- counts(umi.qc)
  rownames(unc) <- rowData(umi.qc)$Symbol
  assign(paste0("counts.",name),unc)
  set.seed(100)
  test <- scran::doubletCells(umi.qc)
  metadata <- data.frame(barcode= substr(colData(umi.qc)$Barcode,0,16),
                         cell_id=sprintf(paste0(name,"_c%d"), 1:dim(umi.qc)[2]),
                         sample_id=rep(name,dim(umi.qc)[2]),
                         total_features=colData(umi.qc)$detected,
                         total_counts=colData(umi.qc)$sum,
                         doublet_score=test)
  gc()
  ###############################################
  #Add lineage info###############################
  ###############################################

 
  reference_lenti <- read.csv(gzfile(file.path(maindir, "annotation", "LG22_filtered.fa.gz")),
                              comment.char = ">",header=F)
  # Top and Bot, and RTop, RBot flanking sequence
  fl <- c("CTAGAACACTCGAGATCAG","TGATACATCATACCACAT","CTGATCTCGAGTGTTCTAG","ATGTGGTATGATGTATCA")
  I = 1
  D = 1
  S = 1

  drop_barcode <- read.table(file = paste0("~/Desktop/scRNAseq_data_local/LineageBarcodes/matched_sequences_",name),sep="\t")
  drop_barcode$barcode <- substr(drop_barcode$V2,0,16) #for files generated by Pacôme
  
  length(unique(drop_barcode$barcode))
  lineage_barcode <- read.table(file = paste0("~/Desktop/scRNAseq_data_local/LineageBarcodes/sequence_withTop_",nameS))

  pos_top = attr(adist(fl[1], lineage_barcode[,1], costs = c(I,D,S), fixed=F, partial=T, counts=T), "offsets")
  lineage_barcode$pos_FTop <- pos_top[,,"first"]
  pos_bot = attr(adist(fl[4], lineage_barcode[1,1], costs = c(I,D,S), fixed=F, partial=T, counts=T), "offsets")
  lineage_barcode$pos_RBot <- pos_bot[,,"first"]
  lineage_barcode$count <- (lineage_barcode$pos_RBot - lineage_barcode$pos_FTop)
  lineage_barcode$LBC <- substr(lineage_barcode$V1,lineage_barcode$pos_FTop+19,lineage_barcode$pos_FTop+38)
  lineage_barcode$length_barcode <-  nchar(lineage_barcode$LBC)
  
  lineage_barcode$LBC[lineage_barcode$length_barcode < 14] <- "short"
  

  unique_lineage <- unique(lineage_barcode$LBC[which(lineage_barcode$LBC!="short")]);

  list_agrep  = sapply(unique_lineage,function(x) agrep(x, reference_lenti$V1, max.distance=2, costs = c(I,D,S), value=F))
  indice_agrep <- unlist(list_agrep)

  if(length(grep("\\d",names(indice_agrep)))>0) {
    indice_agrep = indice_agrep[-grep("\\d",names(indice_agrep))] # remove sequence matching multiple ref
  }

  lineage_barcode$lineage_indice <- indice_agrep[match(substring(lineage_barcode$LBC,1,20),names(indice_agrep))]
  lineage_barcode$tag <- reference_lenti$V1[lineage_barcode$lineage_indice]
  lineage_barcode$lineage_indice[is.na(lineage_barcode$lineage_indice) & lineage_barcode$length_barcode==20] <- "unknown"
  lineage_barcode$lineage_indice[is.na(lineage_barcode$lineage_indice)] <- "N"
  lineage_barcode$tag[lineage_barcode$lineage_indice=="unknown"] <- lineage_barcode$LBC[lineage_barcode$lineage_indice=="unknown"]
  
  
  dim(lineage_barcode)

  metadata$lineage_barcode <- lineage_barcode$tag[match(metadata$barcode,drop_barcode$barcode)]
  metadata$lineage_barcode_ref <- lineage_barcode$lineage_indice[match(metadata$barcode,drop_barcode$barcode)]
  metadata$lineage_barcode_ref[metadata$lineage_barcode_ref=="N"] <- NA
  
  #metadata$lineage_barcode <- NA
  ################################################
  ################################################
  
  assign(paste0("metadata.",nameS),metadata)
  save(list=c(paste0("counts.",nameS),paste0("metadata.",nameS)),file=file.path(RDatadirSamples,paste0(nameS,".RData")))
  
  
}

################################################
############Add AMarie' lineage info############
################################################

for(i in 5:11){
  nameS <- c("MM468_DMSO3_day50","MM468_5FU3_day50","MM468_5FU3_day77","MM468_5FU3_day202","MM468_5FU5_day67","MM468_5FU5_day171","MM468_5FU6_day33","MM468_5FU6_UNC_day33","MM468_UNC_day33","MM468_5FU6_day214","MM468_initial")[i]
  load(file.path(RDatadirSamples,paste0(nameS,".RData")))
  lineage_AM <- read.csv(paste0("~/Desktop/scRNAseq_data_local/LineageBarcodes/","consensus_cell_10xbc_and_vbc_",nameS,"_20_4_annot.csv"))
  lineage_AM$BC_10x <- substr(lineage_AM$BC_10x,0,16)
  
  test <- get(paste0("metadata.",nameS))
  colnames(test)[1] <- "BC_10x"
  test <- left_join(test,lineage_AM)
  
  assign(paste0("metadata.",nameS),test)
  save(list=c(paste0("counts.",nameS),paste0("metadata.",nameS)),file=file.path(RDatadirSamples,paste0(nameS,".RData")))
  rm(list=(paste0("counts.",nameS)))
}



